In [ ]:
import pandas as pd


df = pd.read_csv('../data/processed/ACY_05M.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 7 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   id                                                        66 non-null     int64
 1   Month                                                     66 non-null     object
 2   Initial Decisions                                         66 non-null     int64
 3   Substantive Interviews                                    66 non-null     int64
 4   Total Principal Stages Completed                          66 non-null     int64
 5   Asylum Caseworking Staff                                  66 non-null     float64
 6   Productivity (Principal Stages Per Caseworker Per Month)  66 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 3.7+ KB

,id,Month,Initial Decisions,Substantive Interviews,Total Principal Stages Completed,Asylum Caseworking Staff,Productivity (Principal Stages Per Caseworker Per Month)
0,1,2020-01-01 00:00:00,2332,2304,4636,635.0,7.0
1,2,2020-02-01 00:00:00,2246,2231,4477,616.0,7.0
2,3,2020-03-01 00:00:00,1970,1588,3558,607.0,6.0
3,4,2020-04-01 00:00:00,380,1,381,608.0,1.0
4,5,2020-05-01 00:00:00,1052,1,1053,604.0,2.0